{{- if and .Values.cacheserverSpec .Values.cacheserverSpec.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-cache-server-service"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}-cache-server-service"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/component: "cache-server"
    app.kubernetes.io/part-of: "vllm-stack"
    app.kubernetes.io/managed-by: helm
    {{- include "chart.cacheserverLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: "cache-server-port"
      port: {{ .Values.cacheserverSpec.servicePort }}
      targetPort: {{ .Values.cacheserverSpec.containerPort}}
      protocol: TCP
  selector:
    app.kubernetes.io/name: "{{ .Release.Name }}-cache-server-service"
    {{- include "chart.cacheserverLabels" . | nindent 4 }}
{{- end -}}
